# Generated by Django 6.0.1 on 2026-07-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emeregency_contact',
            new_name='emergency_contact',
        ),
    ]
