# Generated by Django 6.0.1 on 2026-09-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appointment_notification_prescription_vitalsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_surgeries',
            field=models.TextField(blank=True),
        ),
    ]
