# Generated by Django 6.0.1 on 2026-07-07 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(default='timezone.now', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
