# Generated by Django 6.0.1 on 2026-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='approved_by_type',
            field=models.CharField(default='patient', max_length=50),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='emergency_contact_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='emergency_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
