# Generated by Django 6.0.1 on 2026-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('hospital_staff', 'Hospital Staff'), ('admin', 'Admin')], default='patient', max_length=30),
        ),
    ]
