# Generated by Django 6.0.1 on 2026-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital_staff', 'Hospital Staff'), ('admin', 'Admin')], default='patient', max_length=30),
        ),
    ]
